### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by fcolista** [greenbone/ospd-netstat#5]
Hi. Can a release please be tagged, in order to make the life easier for poor distro packagers?
Thanks

**Comment by bjoernricks** [comment]
Hi @fcolista, of course we can do that. But please be aware that all ospd scanners beside ospd-openvas might very likely not work with current ospd. They are in an unmaintained state at the moment.

**Comment by jjnicola** [comment]
I have just created the tag v1.0. It only supports [OSPd v1.3.](https://github.com/greenbone/ospd-netstat/blob/46ceca634555f969c321fec8347e98d11f06a0e7/setup.py#L40)

**Comment by fcolista** [comment]
Thanks.
